version: '3.4'

services:
  catalogExpress:
    image: mongo-express

  catalogdb:
    image: mongo

  basketdb:
    image: redis
  
  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: portainer

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  portainer_data: