version: '3.4'

services:
  rabbit:
    image: rabbitmq

  catalogExpress:
    image: mongo-express

  catalogdb:
    image: mongo

  basketdb:
    image: redis
  
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: portainer

  order.api:
    image: ${DOCKER_REGISTRY-}order.api
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

volumes:
  mongo_data:
  portainer_data:
